import '@radix-ui/themes/styles.css';
import "./globals.css";
import { poppins } from '@/fonts/font';
import { Theme } from '@radix-ui/themes';

export const metadata = {
  title: "Discuss-It | Chat App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${poppins.className}`}>
        <Theme appearance='dark'>
          {children}
        </Theme>
      </body>
    </html>
  );
}
