name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        run: |
          echo "$PRIVATE_KEY" > key.pem
          chmod 600 key.pem

          ssh -i key.pem $EC2_USER@$EC2_HOST "

          if ! command -v nvm &> /dev/null
          then
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
          source ~/.bashrc
          fi
          export NVM_DIR=\"\$HOME/.nvm\"
          [ -s \"\$NVM_DIR/nvm.sh\" ] && \. \"\$NVM_DIR/nvm.sh\"
          nvm install 20
          nvm use 20

          cd /home/ubuntu/discussIt/server &&
            git pull origin main &&
            npm install &&
            sudo systemctl daemon-reload &&
            sudo systemctl restart chat-app.service
          "

          # Remove the SSH key file after use
          rm key.pem
